config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :feed, only: [:index] do
    collection do
      get 'liked'
    end
    member do
      put "like", to: "feed#like"
    end
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  def self.update(feed_url)
    feed = Feedjira::Feed.fetch_and_parse(feed_url)
    feed.entries.each do |article|
      unless exists? :guid => article.id
        create!(
          :title => article.title,
          :url => article.url,
          :published_at => article.published,
          :guid => article.id,
          )
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  has_many :feeds
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || feed_index_path
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!
  before_action :find_feed, only: [:like]

  def index
    @feed = Feed.all.order("published_at Desc").limit(30)
  end

  def like
    @feed.liked_by current_user
    redirect_to :back, notice: "Article liked"
  end

  def liked
    @feed = current_user.find_liked_items
  end

  private

  def find_feed
    @feed  =  Feed.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feed/index.html.erb
<h1 class="title">Reddit Feed</h1>
<div class="wrapper" id="feed">
  <ul>
    <% @feed.each do |feed| %>
      <li><%= link_to h(feed.title), feed.url %> |
      <%= link_to like_feed_path(feed), method: :put do %>
        <i class="fa fa-heart-o"></i>
      <% end %></li>
      <p>Published:<%= feed.published_at.strftime("%x, %X") %> </p>
      <hr>
    <% end %>
  </ul>
</div>

app/views/feed/liked.html.erb
<h1 class="title">Liked Articles</h1>
<div class="wrapper" id="feed">
  <ul>
    <% @feed.each do |liked| %>
      <li><%= link_to h(liked.title), liked.url %></li>
      <hr>
    <% end %>
  </ul>
</div>

app/views/layouts/_header.html.erb
<header id="main-header" class="cf" data-turbolinks-permanent>
  <%= link_to "Reddit Reader", feed_index_path, id: "logo" %>
  <nav>
    <ul>
      <li><%= link_to "My Liked Articles", liked_feed_index_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if alert %>
    <div id="alert-wrapper">
      <p class="alert"><%= alert %></p>
    </div>
  <% elsif notice %>
    <div id="notice-wrapper">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>

  <% unless current_page?(root_path)%>
    <%= render 'layouts/header'; %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div id="background">
  <header class="cf">
    <%= link_to "Reddit Reader", feed_index_path, id: "logo" %>
  </header>


    <div class="wrapper-skinny">
      <h1><%= link_to "RSS Reader", feed_index_path %><i class="fa fa-rss fa-2x"></i></h1>
    <% if !user_signed_in? %>
      <%=link_to "Join Us!", new_user_registration_path, class: "button button-highlight" %>
      <%= link_to "Welcome Back!", new_user_session_path, class: "button button-white" %>
    <% else %>
      <%= link_to "Check out the Feed!",feed_index_path, class: "button button-highlight" %>
    <% end %>
    </div>
</div>